<?php


$list= array('Afghanistan Scout Association',
'Asociacion de Guias y Scouts de Chile',
'Asociacion de Guias y Scouts de Costa Rica',
'Asociacion de Scouts de Bolivia',
'Asociacion de Scouts de El Salvador',
'Asociacion de Scouts de Guatemala',
'Asociacion de Scouts de Honduras',
'Asociacion de Scouts de Mexico, A.C.',
'Asociacion de Scouts de Nicaragua',
'Asociacion de Scouts de Venezuela',
'Asociacion de Scouts del Ecuador',
'Asociacion de Scouts del Paraguay',
'Asociacion de Scouts del Peru',
'Asociacion de Scouts Dominicanos',
'Asociacion Nacional de Scouts de Panama',
'Asociacion Scouts de Colombia',
'Associacao de Escuteiros de Angola',
'Associacao dos Escuteiros de Cabo Verde',
'Associacao dos Escuteiros de Sao Tome e Principe',
'Association des Guides et Scouts de Monaco',
'Association des Scouts du Burundi',
'Association des Scouts du Niger',
'Association des Scouts du Rwanda',
'Association des Scouts et Guides de Mauritanie',
'Association Nationale des Scouts de Guinee',
'Association Scoute du Togo',
'Associazione Guide Esploratori Cattolici Sammarinesi[4]',
'Azarbaycan Skaut Assosiasiyasi',
'Bandalag islenskra Skata',
'Bangladesh Scouts',
'Barbados Boy Scouts Association',
'Belarusian Republican Scout Association',
'Bhutan Scouts Association',
'Boy Scouts of America',
'Boy Scouts of Bahrain',
'Boy Scouts of Liberia',
'Boy Scouts of the Philippines',
'Boy Scouts van Suriname',
'Cambodia Scouts',
'Cercetasii Romaniei',
'Confederation Senegalaise du Scoutisme (federation of several organizations)',
'Cook islands Boy Scouts',
'Corpo Nacional de Escutas da Guine-Bissau',
'Cyprus Scouts Association',
'Eesti Skautide Uhing',
'Egyptian Federation for Scouts and Girl Guides (federation of several organizations)',
'Emirates Scout Association',
'Ethiopia Scout Association',
'Faellesradet for Danmarks Drengespejdere (federation of several organizations)',
'Federacao Escotista de Portugal',
'Federacion de Escultismo en Espana',
'Federation Burkinabe du Scoutisme (federation of several organizations)',
'Federation des Scouts de la Republique democratique du Congo',
'Federation du Scoutisme Tchadien(federation of several organizations)',
'Federation Gabonaise du Scoutisme (federation of several organizations)',
'Federation ivoirienne du Scoutisme (federation of several organizations)',
'Federation Nationale du Scoutisme Marocain',
'Federazione italiana dello Scautismo (federation of several organizations)',
'Fiji Scouts Association',
'Firaisan ny Skotisma eto Madagasikara (federation of several organizations)',
'Gerakan Pramuka',
'Guides and Scouts Movement of Belgium (federation of several organizations)',
'Hayastani Azgayin Scautakan Sharjum Kazmakerputiun',
'Hitachdut Hatsofim Ve Hatsofot Be israel (federation of several organizations)',
'iraq Scout Association',
'ittihodi Scouthoi Tojikiston',
'Jordanian Association for Boy Scouts and Girl Guides',
'Junak - cesky skaut, z. s.',
'Kiribati Scout Association',
'Korea Scout Association',
'Kuwait Boy Scouts Association',
'Latvijas Skautu un Gaidu Centrala Organizacija',
'Lebanese Scouting Federation(federation of several organizations)',
'Les Scouts du Cameroun',
'Les Scouts Tunisiens',
'Lesotho Scouts Association',
'Lietuvos Skautija',
'Liga dos Escuteiros de Mocambique',
'Luxembourg Boy Scouts Association (federation of several organizations)',
'Magyar Cserkeszszovetseg',
'Mongolyn Skautyn Kholboo',
'Movimiento Scout del Uruguay',
'Myanmar Scout',
'National Organization of Scouts of Ukraine',
'National Organization of Vietnam Scouts',
'National Scout Organization of Thailand',
'Nepal Scouts',
'Organizatia Nationala A Scoutilor Din Moldova',
'Organization of the Scout Movement of Kazakhstan',
'Organizatsia Na Bulgarskite Skauty',
'Pakistan Boy Scouts Association',
'Palestinian Scout Association',
'Persekutuan Pengakap Malaysia',
'Persekutuan Pengakap Negara Brunei Darussalam',
'Pfadfinder und Pfadfinderinnen Liechtensteins',
'Pfadfinder und Pfadfinderinnen osterreichs',
'Polynesia Scouts Council',
'Public Scout and Girl Guide Movement',
'Ring deutscher Pfadfinderverbande (federation of several organizations)',
'Russian Association of Scouts/Navigators',
'Sakartvelos Skauturi Modzraobis Organizatsia',
'Saudi Arabian Boy Scouts Association',
'Savez izvidaca Bosne i Hercegovine',
'Savez izvidaca Crne Gore',
'Savez izvidaca Hrvatske',
'Savez izvidaca Srbije',
'Scout Association of Hong Kong',
'Scout Association of Japan',
'Scout Association of Nigeria',
'Scout Association Solomon islands Branch',
'Scouterna',
'Scouting Antiano',
'Scouting Aruba',
'Scouting ireland',
'Scouting Nederland',
'Scoutisme Beninois',
'Scoutisme Francais (federation of several organizations)',
'Scouts & Guides of New Caledonia',
'Scouts Australia',
'Scouts Canada, with which is affiliated the Association des Scouts du Canada',
'Scouts de Argentina',
'Scouts d Haiti',
'Scouts Musulmans Algeriens',
'Scouts New Zealand',
'Scouts of Namibia',
'Scouts of Syria',
'Scouts South Africa',
'Seychelles Scout Association',
'Sierra Leone Scouts Association',
'Skaots blong Vanuatu The Scout Association of Vanuatu',
'Slovensky skauting',
'Sojuz na izvidnici na Makedonija',
'Soma Hellinon Proskopon',
'South Sudan Scout Association[5]',
'Speidernes Fellesorganisasjon(federation of several organizations)',
'Sri Lanka Scout Association',
'Sudan Scouts Association',
'Suomen Partiolaiset - Finlands Scouter ry',
'Swaziland Boy Scouts Association',
'Swiss Guide and Scout Movement',
'Tanzania Scouts Association',
'The Bharat Scouts and Guides',
'The Botswana Scouts Association',
'The Gambia Scout Association',
'The General Association of the Scouts of China',
'The Ghana Scout Association',
'The Kenya Scouts Association',
'The Mauritius Scout Association',
'The National Organisation for Scouts and Guides',
'The Saint Lucia Scout Association',
'The Scout and Guide Association of Qatar',
'The Scout Association',
'The Scout Association of Belize',
'The Scout Association of Dominica',
'The Scout Association of Grenada',
'The Scout Association of Guyana',
'The Scout Association of Jamaica',
'The Scout Association of Macau',
'The Scout Association of Malawi',
'The Scout Association of Maldives',
'The Scout Association of Malta',
'The Scout Association of Mongolia',
'The Scout Association of Papua New Guinea',
'The Scout Association of Saint Vincent and the Grenadines',
'The Scout Association of the Bahamas',
'The Scout Association of Tonga Branch',
'The Scout Association of Trinidad and Tobago',
'The Scout Association of Zimbabwe',
'The Scout Association Samoa',
'The Singapore Scout Association',
'The Uganda Scouts Association',
'TUrkiye Izcilik Federasyonu',
'Tuvalu Scout Association',
'Uniao dos Escoteiros do Brasil',
'Uniao Nacional dos Escuteiros de Timor Leste',
'Wezombeli',
'Yemen Scouts and Guides Association - Scout branch',
'Zambia Scouts Association',
'Zveza tabornikov Slovenije',
'Zwiazek Harcerstwa Polskiego',
'Other');
echo json_encode($list);

?>